name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Updated to the latest version

    - name: Set up Python
      uses: actions/setup-python@v4 # Updated to the latest version
      with:
        python-version: 3.8

    - name: Cache conda packages
      uses: actions/cache@v3 # Using the latest version
      with:
        path: ~/.conda/envs/venv
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3 # Updated to the latest version
      with:
        python-version: 3.8
        activate-environment: venv
        environment-file: wine_example\environment.yml
        auto-update-conda: true

    - name: Verify conda installation
      run: conda info

    - name: Run MLFlow
      shell: bash -l {0}
      run: |
        conda init bash
        source ~/.bashrc
        conda activate venv
        mlflow run wine_example
