

name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CSV_URL: "http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
  TARGET_VAR: "quality"
  ALPHA: 0.9
  L1_RATIO: 0.9
  RANDOM_STATE: 42

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8
        activate-environment: wine_example_env
        environment-file: environment.yml
        auto-update-conda: true

    - name: Verify conda installation
      run: conda info

    - name: Run MLFlow
      run: |
        conda activate wine_example_env
        mlflow run wine_example