name: CI

on:
  push:
    branches:
      - master

env:
  CSV_URL: "http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
  TARGET_VAR: "quality"
  ALPHA: 0.9
  L1_RATIO: 0.9
  RANDOM_STATE: 42

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Cache conda packages
      uses: actions/cache@v3
      with:
        path: ~/.conda/envs/venv
        key: ${{ runner.os }}-conda-${{ hashFiles('wine_example/environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.8
        activate-environment: venv
        environment-file: wine_example/environment.yml
        auto-update-conda: true

    - name: Verify conda installation
      run: conda info

    - name: Activate conda environment and run MLFlow
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate venv
        mlflow run wine_example
      shell: bash -l {0}
